a = input().split()
b = input().split()
c = input().split()
d = input().split()
e = input().split()
a[0], a[1], a[2] = int(a[2]),int(a[1]), a[0].lower()
b[0], b[1], b[2] = int(b[2]),int(b[1]), b[0].lower()
c[0], c[1], c[2] = int(c[2]),int(c[1]), c[0].lower()
d[0], d[1], d[2] = int(d[2]),int(d[1]), d[0].lower()
e[0], e[1], e[2] = int(e[2]),int(e[1]), e[0].lower()
listNama = [a,b,c,d,e]
listNama.sort()
print(listNama[2][2])